export const EError = {
    ROUTING_ERROR: 1, // RUTA NO EXISTE
    DATABASE_ERROR: 2, // ERROR EN LA BASE DE DATOS
    INVALID_JSON: 3, // JSON INVALIDO
    AUTH_ERROR: 4, // ERROR DE AUTENTICACION
    INVALID_PARAM: 5, // ERROR DE PARAMETROS EN LA RUTA
    PRODUCT_CREATION_ERROR: 6, // ERROR AL CREAR PRODUCTO EN BASE DE DATOS
    CART_CREATION_ERROR: 7 // ERROR AL CREAR CARRITO EN BASE DE DATOS
};